// React application/src/Components/Home.jsx
import React from "react";
import "./Home.css";
import { Link } from "react-router-dom";
export default function Home() {
  return (
    <div className="hero">
      <div className="home hero-content">
        <h1>Welcome to ShopEase</h1>
        <p>Your one-stop shop for all your daily needs.</p>
        <p>Discover a wide range of products at unbeatable prices.</p>
        <p>Join our community and enjoy exclusive offers.</p>
        <Link to="/products" className="btn btn-primary btn-lg">
          {" "}
          Shop Now
        </Link>
      </div>
    </div>
  );
}

// Angular application/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { ProductComponent } from '../product/product.component';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [ProductComponent, RouterModule, FormsModule, CommonModule],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  constructor(public authService: AuthService) {}
  logout() {
    this.authService.logout();
  }
}

<div class="container">
  <div class="hero">
    <div class="container hero-content">
      <h1>Welcome to ShopEase</h1>
      <p>Your one-stop shop for all your daily needs.</p>
      <p>Discover a wide range of products at unbeatable prices.</p>
      <p>Join our community and enjoy exclusive offers.</p>
      <a routerLink="/product" class="btn btn-primary btn-lg">Shop Now</a>
    </div>
  </div>

  <div (click)="logout()" *ngIf="authService.isLoggedIn()" class="logout">
    <button class="btn btn-primary btn-lg">Log Out</button>
  </div>
</div>
